task 6 on branch6 complted with tests
Szpytma/be-nc-games pull request #4
Opened 2023-03-28 15:26 UTC by Szpytma

2023-03-28 15:45 UTC, alexdevdavis requested changes
Here are some extra tests to add before this can be considered done:
- when review_id is invalid (status 400)
- when review_id valid but not found (status 404)
- when the review exists, but has no comments (status 200)


Perhaps you've written some of these in the past; check your commit history if you feel you have, as you may easily be able to add them to this branch and save a bunch of time

2023-03-28 19:45 UTC, Szpytma commented
@alexdevdavis 
when review_id is invalid (status 400) - completed
when review_id valid but not found (status 404) - completed
when the review exists, but has no comments (status 200) - I guess I need to create a func checking if the review exists and then grab all promises - something as we did on today lecture, I was trying to complete it today but I was struggling

2023-03-29 08:26 UTC, alexdevdavis approved these changes
Happy to approve this PR. Well done 😎 
- just the one error message to edit, and it's 💯 . No need to submit another PR for this ticket, though; I'm very happy with the work you've done here

2023-03-29 08:26 UTC, alexdevdavis commented on __tests__/app.test.js
> +        expect(body.message).toBe("Index outOfBound");
I wonder if `review not found` might be a more useful message

2023-03-29 08:26 UTC, alexdevdavis commented on models/reviews.model.js
> +      return Promise.reject({ status: 404, message: "Index outOfBound" });
No sure where Index outOfBound has come from, but it doesn't reflect what the user is trying to do, so I'd suggest changing it

2023-03-29 08:34 UTC, merged