Task 11 completed
Szpytma/be-nc-games pull request #9
Opened 2023-03-30 15:04 UTC by Szpytma

- updated readme.md
- implemented queries for reviews this endpoint accepts 'category', 'sort_by' & 'order' as quarries.
Waiting for approval

2023-03-30 15:16 UTC, robert112233 requested changes
Good attempt. There are some more tests to include, make the changes and submit another PR for review.

2023-03-30 15:16 UTC, robert112233 commented on __tests__/app.test.js
> +      });
If the category is not found it should be 404 - not found

2023-03-30 15:16 UTC, robert112233 commented on __tests__/app.test.js
> +  });
This is a good start on the tests. You are missing tests for:
400 invalid sortBy - sort_by=notTitle. 
400 invalid order - order=ascending&desc_at_the_same_time 

There is one happy path test 200: where you sort by a category that exists but has no associated reviews - returns []

2023-03-31 11:32 UTC, Szpytma commented on __tests__/app.test.js
> +  });
the last case took ages to fix! but its sorted now

2023-03-31 13:43 UTC, alexdevdavis approved these changes
Looking good. 
- I'd suggest adding some mention of the node and postgres versions, for compatibility's sake

2023-03-31 13:43 UTC, alexdevdavis commented on README.md
> +## To see possible endpoints please go to api/
should this be `/api`

2023-03-31 14:03 UTC, merged